### PR TITLE
Implement Drive for concrete container types

### PR DESCRIPTION
**Pull request by andylokandy**
Closes https://github.com/nikis05/derive-visitor/issues/16

### CODE REVIEW

**Review by lovasoa — DISMISSED** [review]

**Comment by Xuanwo** [comment]
Hi, @nikis05, are you willing to take a look and get this PR merged? I believe this is valuable to all existing users.

**Comment by nikis05** [comment]
@Xuanwo yes, just need to find the time to review. I will try to have a look tomorrow

**Comment by nikis05** [comment]
@andylokandy thanks for your contribution, this looks good! Could you kindly bump the version of the crate and the macros crate to 0.4.0 in Cargo.toml?

**Comment by andylokandy** [comment]
@nikis05 No problem

**Review by nikis05 — APPROVED** [review]

**Pull request merged**
